version: '3.8'

services:
  db:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    container_name: asset_analysis_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: asset_analysis
    ports:
      - "5432:5432"
    # volumes:
    #   - db_data:/var/lib/postgresql/data

# volumes:
#   db_data:
